# Graphical editor
capsulecolor = "black"
cancolor = "white"
labcolor = "azure"
portcolor = "lavender"
testercolor = "beige"
loggercolor = "cadetblue3"
commentcolor = "gold"
commentfont = "times"
functioncolor = "grey"
functionfont = ("courier", 8)
timercolor = "darkolivegreen2"
triggercolor = "darkorange"
dataflowcolor = "grey"
messagecolor = "black"
transitioncolor = "blue"
procedurecolor = "purple"
callcolor = "purple"
statecolor = "blue"
midpointcolor = "yellow"
notecolor = "yellow"
camPathcolor = "grey"
startcolor = "black"
locatecolor = "red"
locatecooledcolor = "green"
resizecolor = "yellow"
scorchcolor = "red"
titlebgcolor = "white"
select = "red"
# debugging
visited = "green"
highlight = "red"
exclusive = "red"
# Text editor
keyword = "purple"
reserved = "blue"
background = "white"
# MessageWindow
mwColors = {"normal": "black", "error": "red",  "dbg": "blue"}
