CAPSULE INTERFACE CapAmbig ;
PORT p1 : PROTOCOL
   INCOMING MESSAGE a() ;
END;
PORT p2 : PROTOCOL
   INCOMING MESSAGE a() ;
END;
PORT test : PROTOCOL
   INCOMING MESSAGE start() ;
   INCOMING MESSAGE summary() ;
END
END CapAmbig.
