INTERFACE CapParTypes;

TYPE c1Pro = PROTOCOL
  INCOMING MESSAGE m1();
  OUTGOING MESSAGE r1();
END;
TYPE c2Pro = PROTOCOL
  INCOMING MESSAGE m2();
  OUTGOING MESSAGE r2();
END;

TYPE parPro = c1Pro @ c2Pro;

END CapParTypes.
