CAPSULE INTERFACE CapSynchChild1 ;
PORT p1 : PROTOCOL
   INCOMING MESSAGE asyn() ;
END;
PORT p2 : PROTOCOL
   OUTGOING MESSAGE aCheck(i : INTEGER) ;
   SYNCHRONOUS OUTGOING MESSAGE sCheck(i : INTEGER) ;
END
END CapSynchChild1.
