call ce -C --print  CapAgr
call ce -C --print  CapAmbig
call ce -C --print  CapAmbigTrans
call ce -C --print  CapAssert
call ce -C --print  CapConj
call ce -C --print  CapDataport
call ce -C --print  CapExp
call ce -C --print  CapIntState
call ce -C --print  CapMain
call ce -C --print  CapProc
call ce -C --print  CapProto 
call ce -C --print  CapRTC1
call ce -C --print  CapReset
call ce -C --print  CapScale
call ce -C --print  CapSynch
call ce -C --print  CapTimer 
call ce -C --print  CapTimerExtreme 
call ce -C --print  CapTimerNest1
call ce -C --print  CapTrigger 
call ce -C --print  CapTriggerNest1 
call ce -C --print  CapType
call ce -C --print  CapTypeNest 
