call m3 Log.*3 -m 
call CapNest -m 
call CapProc -m 
call CapTimer -m 
call CapTimerNest -m 
call CapTrigger -m 
call CapTriggerNest -m 
call CapRTC -m 
call CapIntState -m 
call CapTimerExtreme -m 
call CapType -m  
call CapProto -m 
call CapSwapper -m 
call CapAmbig -m 
call CapAmbigTrans -m 
call CapTypeNest -m 
call CapReset -m 
call CapSynch -m 
call CapDataport -m 
call CapScale -m 
call CapAgr -m 
call CapAssert -m
call CapExp -m
call CapConj -m
call CapPar -m
call CapBroad -m
call CapStrictState -m
call CapTestValue -m
call CapReply -m