
CAPSULE INTERFACE CapBig ;
PORT p1 : PROTOCOL
    INCOMING MESSAGE a() ;
    INCOMING MESSAGE b() ;
    INCOMING MESSAGE c() ;
    INCOMING MESSAGE d() ;
    INCOMING MESSAGE e() ;
    INCOMING MESSAGE f() ;
    INCOMING MESSAGE g() ;
    INCOMING MESSAGE h() ;
    INCOMING MESSAGE i() ;
    INCOMING MESSAGE j() ;
    INCOMING MESSAGE k() ;
    INCOMING MESSAGE l() ;
    INCOMING MESSAGE m() ;
END;
END CapBig.