CAPSULE INTERFACE CapSynchChild2 ;
PORT p1 : PROTOCOL
   INCOMING MESSAGE aCheck(i : INTEGER) ;
   SYNCHRONOUS INCOMING MESSAGE sCheck(i : INTEGER) ;
   SYNCHRONOUS INCOMING MESSAGE varCheck(VAR i : INTEGER) ;
END;
END CapSynchChild2.
