ce.sh -C --print  CapAgr
ce.sh -C --print  CapAmbig
ce.sh -C --print  CapAmbigTrans
ce.sh -C --print  CapAssert
ce.sh -C --print  CapConj
ce.sh -C --print  CapDataport
ce.sh -C --print  CapExp
ce.sh -C --print  CapIntState
ce.sh -C --print  CapMain
ce.sh -C --print  CapProc
ce.sh -C --print  CapProto 
ce.sh -C --print  CapRTC1
ce.sh -C --print  CapReset
ce.sh -C --print  CapScale
ce.sh -C --print  CapSynch
ce.sh -C --print  CapTimer 
ce.sh -C --print  CapTimerExtreme 
ce.sh -C --print  CapTimerNest1
ce.sh -C --print  CapTrigger 
ce.sh -C --print  CapTriggerNest1 
ce.sh -C --print  CapType
ce.sh -C --print  CapTypeNest 
