alltests = ["AnonTest",
  "ArrayTest",
  "BoolTest",
  "Case",
  "Char",
  "ComplExp",
  "Const",
  "Ctor",
  "Deref",
  "Dispose",
  "EnumTest",
  "Eval",
  "ExcModUser",
  "Exception",
  "Exit",
  "ExprTest",
  "FirstLast",
  "ForTest",
  "Format",
  "StackUser",
  "IOTest ",
  "IfTest",
  "ImpAs",
  "InitTest",
  "MethodInh",
  "ObjectMethods",
  "Multi",
  "NilTest",
  "Numerics",
  "ObjectFields",
  "OpaqueUser",
  "OpenArray",
  "Overrides",
  "PartUser",
  "Predef",
  "Proc",
  "ProcType",
  "RecNasty",
  "RecRef",
  "RecTest",
  "RefRec",
  "RefTest",
  "Set",
  "SubArray",
  "SubType",
  "TCase",
  "SortTree",
  "TryFinally",
  "TypeCode",
  "VarType",
  "With ",
]

import os
for test in alltests:
    print os.popen("pyrun %s" % test).read()
    
