ce.sh Account --screenshot --no-XML-server
ce.sh ATM --screenshot --no-XML-server
ce.sh Bank --screenshot --no-XML-server
ce.sh ATMState --screenshot --no-XML-server
ce.sh Interest --screenshot --no-XML-server
ce.sh BankInterest --screenshot  --no-XML-server
ce.sh ATMTimeout --screenshot --no-XML-server
ce.sh ATMSafe --screenshot --no-XML-server
ce.sh C1 --screenshot --no-XML-server
ce.sh pytimer --screenshot --no-XML-server
ce.sh pytrigger --screenshot --no-XML-server
ce.sh pyact --screenshot --no-XML-server
ce.sh ConjParent --screenshot --no-XML-server