import tpg
import os
import sys
import stat

def metaCompile():
    ra_home = os.environ['M3_HOME']
    if ra_home[0] == '"':
        ra_home = ra_home[1:-1]
    sourcedir = ra_home + os.sep + "src" + os.sep + "rts"
    gramfile = sourcedir + os.sep + "SystemGrammar.g"
    pyfile = sourcedir+ os.sep + "SystemGrammar.py"
    if os.path.exists(pyfile) and (os.stat(gramfile)[stat.ST_MTIME] < os.stat(pyfile)[stat.ST_MTIME]):
        return
    print "Recompiling System Language Grammar"

    grammar = open(gramfile).read()
    srcfile = open(pyfile,"w")
    srcfile.write("""
# This file is automatically generated. ALL EDITS WILL BE LOST !!!!
# Make changes in SystemGrammar.g if you must
import tpg
class Cmd(tpg.Parser):    
""")
    srcfile.write('   r"""\n')
    srcfile.write(grammar)
    srcfile.write('\n"""\n')
    srcfile.close()
    
if __name__ == "__main__":
    metaCompile()
