ce.sh Account --print --no-XML-server
ce.sh ATM --print --no-XML-server
ce.sh Bank --print --no-XML-server
ce.sh ATMState --print --no-XML-server
ce.sh Interest --print --no-XML-server
ce.sh BankInterest --print  --no-XML-server
ce.sh ATMTimeout --print --no-XML-server
ce.sh ATMSafe --print --no-XML-server
ce.sh C1 --print --no-XML-server
ce.sh pytimer --print --no-XML-server
ce.sh pytrigger --print --no-XML-server
ce.sh pyact --print --no-XML-server
ce.sh ConjParent --print --no-XML-server