The modes and their effects are as follows
\begin{itemize}
\item Move : The default mode, you can move objects by dragging them around the window or you can resize them if you click over a corner of an object while it is red
\item Select : In this mode you can drag to create a box around items which you can then either move as a group in move mode or manipulate in other useful ways together in align mode
\item Align : Acts on the currently selected set of objects and allows you to line them up, evenly distribute them or make them all the same size
\item New Object : Create new objects, for each left click a menu of possible objects is shown, once a selection has been made a dialog is presented asking for the necessary details
\item Locate : clicking on any graphical item will highlight its source in the text window
\item Explain : selectively show and hide connections from all or selected avatars
\item New Connection : Create new connections: simply drag from the source object to the target object, the tool will guess what you want to do
\end{itemize}
