The first group covers mode changes (see more on modes below)
\begin{itemize}
\item move : Go into move mode
\item select : Go into select mode
\item new object : Go into new object mode
\item connect : Go into connect mode
\item align : Go into align mode
\item locate : Go into locate mode
\item explain : Go into explain mode
\end{itemize}
The second group covers printing
\begin{itemize}
\item print : Generate scaled postscript and png of the complete design canvas (works on capsules of arbitrary size and complexity)
\item gen scene : generate a povray scene file, only interestingif you have Povray installed on your computer and you want to impress people with three dimensional models
\end{itemize}
Finally we have some other functions
\begin{itemize}
\item open : Open a new or existing capsule
\item save : save and generate code for current capsule
\item undo : undo the last change to the model text (graphics-only changes not included)
\item redo : redo what was undone
\item redraw : reparse and redraw the current capsule
\item reload : reload the source files of the current capsule (e.g. if they have been edited by another tool)
\item test : dump a list of avatars to console (for internal test purposes)
\item run : run the system with the default input file
\item debug : start a debug run (see section on debugging below)
\item options : change various options at run time (instead of using command line)
\item input : edit and manage the input file used for a test run
\end{itemize}
